### PR TITLE
Aph/puppetserver ca update

### PR DESCRIPTION
**Pull request by m0dular**

### CODE REVIEW

**Comment by natemccurdy** [comment]
@sensei-de-loafage Hi! Thanks for the PR. Sorry for the delay... I didn't get a notification that this was here. You can @ my name in the future and that will notify me.

Glad to see you updating this for Puppet 6. That's a good change.
But can I ask that you rebase and split your commits out a bit. Seems like you're doing a few things beyond just updating the cert clean command.

Also, I've already updated the PDK files to 1.9, so no need for that in your PR.

Thanks again.

**Comment by m0dular** [comment]
Hi @natemccurdy,

Thanks for the feedback.  I see you created a new `puppetserver6` branch with support for the `puppetserver ca` command.  Do you still want me to clean up this PR?

**Comment by natemccurdy** [comment]
@sensei-de-loafage Actually, yeah... If you can hold off for now, I'll be updating this module quite a bit. Adding puppetserver 6 support as well as restructuring the code.

You can leave the PR for now and re-visit it after I cut a new release.

**Comment by natemccurdy** [comment]
@sensei-de-loafage Thanks again for your submission! I'm going to close this PR out though as all the features that would have been added already exist now.

Please let me know (via an issue) if the new module versions doesn't suit all your use cases.

**Pull request closed without merging**
